{% set version = "1.10.0" %}

package:
  name: metar
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/metar/metar-{{ version }}.tar.gz
  sha256: 3c43f65fc86b52fb592e0e5ed8034636eabc9f9a1c6930a2de406aab6ba96f0e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - metar

about:
  home: http://github.com/python-metar/python-metar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    python-metar is a python package that parses coded METAR weather reports.
  description: |
    python-metar is a python package that parses coded METAR weather reports.
  doc_url: https://github.com/python-metar/python-metar
  dev_url: https://github.com/python-metar/python-metar

extra:
  recipe-maintainers:
    - phobson
    - akrherz
