{% set version = "1.8.0" %}

package:
  name: metar
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/metar/metar-{{ version }}.tar.gz
  sha256: d23494c5dcb81a857de9f4022cab0cf3d37277a32f675a9e1491e817d56f8428

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - metar

about:
  home: http://github.com/python-metar/python-metar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    python-metar is a python package that parses coded METAR weather reports.
  description: |
    python-metar is a python package that parses coded METAR weather reports.
  doc_url: https://github.com/python-metar/python-metar
  dev_url: https://github.com/python-metar/python-metar

extra:
  recipe-maintainers:
    - phobson
    - akrherz
