travis:
  secure:
    BINSTAR_TOKEN: QH54hxg76ybgQcR+GruZ8MoIkBaImv/ujFC4A2rRafLt82twiKgFfmvL3tolPktnnfurEWYgsZo5GjPc8kiXcykD4uMaQndoTeD/QlA8lmXy2DO6vnEf/GRxkamWpC0cJLxhIqVOIs7wLzxPhu4gahhEohx2y4am8ph37q6ruV9OskTCm5nQGvLcLq7ClUyiHO/WT2fSCT8ovPkd/hfq5HOjMMDVWDsmM2rnvVcIlpOCIkfmei8sk9rT4HFtuBGgbaCa5PlrI86tGNFAr50IQKAv3Jj8v0ihmkJa3Fgf1M+Ill7UzNrmi6YUbT/nQLt8uCapH9Ix2Ys5fqDUR7ASds0rd93jFEwefTDme5alsaa9QqlbTOXawSO+SDjOdR6JwLdgJHKEizBLZGBwgadw9F2DSvIb15XnogkKKpPaGIQKxx0GWAxXAEol+1m16pWQRnqcSMM3QHrQNBEWLYuWIrM16/HyLagTwJZ1+hzpevpmbgQyUzyJJD5FFjWVwnwMNI6G9P5bZJGKCjelcYbvMNbanS/FxWEkA9tgUpvgdQEG1ImfU5snCbE27rlR+ntelAitQd0N6/iKjxttbcicE5jRPc9Tcu9Jhbh7jiBW19RhHtfHDPaatE2wPOrbSoV/EwY2+yFwqPotuPw4jQzzfpHtaJ+1V1R5JyvZHKtAWMI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
